package ru.stqa.jft.addressbook.tests;// Generated by Selenium IDE
import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import ru.stqa.jft.addressbook.appmanager.ContactData;

public class ContactCreationTests extends TestBase{

  @Test
  public void testCreateContact() {
    app.getNavigationHelper().goToAddNewPage();
    app.getContactHelper().fillContactForm(new ContactData("Pavel", "Alekseev", "Pavlikovich", "Prrr", "BSPB", "Saint-Petersburg", "4637465", "alexeew.ps@mail.ru", "30", "July", "1992"));
    app.getContactHelper().submitContactCreate();
  }


}
