package ru.stqa.jft.addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;
import ru.stqa.jft.addressbook.model.GroupData;

public class GroupCreationTests extends TestBase{

    @Test
    public void testCreateGroup() {
        app.goToGroupPage();
        app.initGroupCreation();
        app.fillGroupForm(new GroupData("Test2", "Test", "Test"));
        app.submitGroupCreation();
        app.returnToGroupPage();
    }

}
