package ru.stqa.jft.addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;
public class GroupDeletionTests extends TestBase{

  @Test
  public void testGroupDeletion() {
    app.goToGroupPage();
    app.selectGroup();
    app.deleteSelectedGroups();
    app.returnToGroupPage();
  }

}
