package ru.stqa.jft.addressbook;// Generated by Selenium IDE

import org.junit.Test;

public class GroupCreationTests extends TestBase{

    @Test
    public void testCreateGroup() {
        goToGroupPage();
        initGroupCreation();
        fillGroupForm(new GroupData("Test2", "Test", "Test"));
        submitGroupCreation();
        returnToGroupPage();
    }

}
